In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main dataype in ndarray
a1 = np.array([1,2,3,4])

In [3]:
type(a1)

numpy.ndarray

In [144]:
a2 = np.array([[1,2,3,4],[1,2,3,4],[0.5,0.6,0.7,0.8]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a3.ndim

3

In [10]:
a1.dtype

dtype('int64')

In [12]:
a3.size

18

In [14]:
type(a1)

numpy.ndarray

In [18]:
## Create a DataFram from a NumPy array
import pandas as pd

df1 = pd.DataFrame(a1)
df2 = pd.DataFrame(a2)

In [20]:
df1

0
0  1
1  2
2  3
3  4

## Ceating Array

In [22]:
one = np.ones(2)

In [23]:
zeros = np.zeros(3)

In [43]:
range_array = np.arange(1,10,1)

(9,)

In [29]:
random_array = np.random.randint(50, 1000, 50)

In [40]:
random_array_1 = np.random.random((50, 1000, 50))
random_array_1.shape

(50, 1000, 50)

In [61]:
random_array_2 = np.random.rand(50, 1000, 50)
random_array_2.shape

(50, 1000, 50)

In [52]:
# Pseudoe-random numbers
np.random.seed(1)

random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]], dtype=int32)

## Viewing array and Metrices

In [54]:
np.unique([1,2,1,2,1,2,1,2])

array([1, 2])

In [55]:
np.unique(random_array_2)

array([6.37851081e-08, 1.78466231e-06, 2.28581850e-06, ...,
       9.99998197e-01, 9.99999517e-01, 9.99999886e-01], shape=(2500000,))

In [58]:
random_array_2[0][0][0]

np.float64(0.34803152205682963)

In [62]:
random_array_2[0][0][0:5] == random_array_2[0,0,0:5]

array([ True,  True,  True,  True,  True])

In [66]:
random_array_2[:,:2,0:1]

array([[[2.04452250e-01],
        [6.94400158e-01]],

       [[3.74877507e-02],
        [8.09591487e-01]],

       [[3.17101513e-01],
        [4.28568738e-02]],

       [[5.31524399e-02],
        [7.75138009e-01]],

       [[4.09525353e-01],
        [2.59145235e-01]],

       [[7.98454498e-01],
        [2.56747000e-02]],

       [[2.93253977e-01],
        [7.79305149e-01]],

       [[6.58925264e-01],
        [8.43332275e-01]],

       [[6.61666668e-01],
        [6.60085497e-01]],

       [[5.20832389e-01],
        [5.71577178e-01]],

       [[5.12277040e-01],
        [4.89753500e-01]],

       [[4.86585313e-01],
        [2.73255569e-01]],

       [[5.20784480e-01],
        [4.78808894e-01]],

       [[4.59386048e-01],
        [9.61445072e-01]],

       [[9.61812044e-01],
        [5.69067658e-01]],

       [[7.48424675e-01],
        [2.54878489e-01]],

       [[4.73066349e-01],
        [4.00353561e-01]],

       [[1.65439365e-02],
        [1.73480729e-01]],

       [[1.02226760e-01],
  

## Manipulation & comparing arrays

In [74]:
ones = np.ones(4)

In [82]:
array_1 = np.array([1,2,3,5])

In [75]:
ones + array_1

array([2., 3., 4., 6.])

In [83]:
array_2 = np.array([[1,2,3,4],[5,6,7,8]])

In [84]:
array_1 * array_2

array([[ 1,  4,  9, 20],
       [ 5, 12, 21, 40]])

In [85]:
a2

array([[1. , 2. , 3. , 4. ],
       [1. , 2. , 3. , 4. ],
       [0.5, 0.6, 0.7, 0.8]])

In [86]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [88]:
a1 // a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 3., 4., 4.]])

In [89]:
a1 / a2

array([[1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [2.        , 3.33333333, 4.28571429, 5.        ]])

In [90]:
a1 ** a2

array([[  1.        ,   4.        ,  27.        , 256.        ],
       [  1.        ,   4.        ,  27.        , 256.        ],
       [  1.        ,   1.51571657,   2.15766928,   3.03143313]])

## Aggregation
Aggration = performin the same operation on a number of thing

In [92]:
listy_list = [1,2,3]
sum(listy_list)

6

In [94]:
listy_nplist = np.array(listy_list)

In [96]:
np.sum(listy_nplist)

np.int64(6)

In [97]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [98]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

12.7 ms ± 475 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
70.2 μs ± 4.77 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [101]:
np.min(a2)

np.std(a2) # strand devaition
np.var(a2) # Variance

np.float64(1.5980555555555551)

## Reshiping & transposing

In [120]:
a2_1 = np.array([[1,2,3],[1,2,3],[0.5,0.6,0.7]])
a3_1 = np.array([[[1,2,3],[1,2,3],[0.5,0.6,0.7]], [[1,2,3],[1,2,3],[0.5,0.6,0.7]]])

In [128]:
a2_1_reshape = a2_1.reshape(1, 3,3)

In [126]:
a2_1_reshape.shape

(3, 3, 1)

In [129]:
a2_1_reshape * a3_1

array([[[1.  , 4.  , 9.  ],
        [1.  , 4.  , 9.  ],
        [0.25, 0.36, 0.49]],

       [[1.  , 4.  , 9.  ],
        [1.  , 4.  , 9.  ],
        [0.25, 0.36, 0.49]]])

## Dot product

In [132]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [133]:
# Elemnt wise multiplication
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [134]:
# Dot prodect
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [138]:
# Transpose mat1
mat2_t  = mat2.T

In [139]:
# Dot prodect
np.dot(mat1, mat2_t)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

## Comparison Operators

In [140]:
a1 > a2

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [141]:
a2 > a1

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [145]:
a2 == a1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [148]:
a2 is a1

False

In [146]:
a2 > 5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [147]:
a2 < 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Sorting Arra

In [152]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[9, 4, 4, 6, 4],
       [4, 3, 4, 4, 8],
       [4, 3, 7, 5, 5]], dtype=int32)

In [153]:
np.sort(random_array)

array([[4, 4, 4, 6, 9],
       [3, 4, 4, 4, 8],
       [3, 4, 5, 5, 7]], dtype=int32)

In [154]:
np.argsort(random_array)

array([[1, 2, 4, 3, 0],
       [1, 0, 2, 3, 4],
       [1, 0, 3, 4, 2]])

In [158]:
np.argmin(random_array, axis=0), random_array

(array([1, 1, 0, 1, 0]),
 array([[9, 4, 4, 6, 4],
        [4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5]], dtype=int32))

In [160]:
np.argmin(random_array, axis=1), random_array

(array([1, 1, 1]),
 array([[9, 4, 4, 6, 4],
        [4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5]], dtype=int32))

## Pracical Exemple - NumPy in Action!!!

<img src="images/IMG_8751.JPG"/>

In [163]:
# Turn the image into a NumPy array
from matplotlib.image import imread
kerenel = imread("images/IMG_8751.JPG")
print(kerenel.size, kerenel.shape, kerenel.ndim)

5235840 (1080, 1616, 3) 3


In [164]:
kerenel

array([[[ 9,  7, 12],
        [ 9,  7, 12],
        [ 8,  6, 11],
        ...,
        [21, 21, 19],
        [21, 21, 19],
        [21, 21, 19]],

       [[12,  6, 10],
        [11,  5,  9],
        [ 9,  4,  8],
        ...,
        [21, 21, 19],
        [21, 21, 19],
        [21, 21, 19]],

       [[11,  7,  8],
        [11,  7,  8],
        [11,  7,  8],
        ...,
        [22, 23, 18],
        [22, 23, 18],
        [22, 23, 18]],

       ...,

       [[45, 24, 63],
        [43, 22, 61],
        [43, 22, 61],
        ...,
        [76, 76, 52],
        [76, 76, 52],
        [77, 77, 53]],

       [[45, 28, 64],
        [39, 22, 58],
        [37, 20, 56],
        ...,
        [76, 76, 52],
        [76, 76, 52],
        [76, 76, 50]],

       [[38, 24, 57],
        [34, 20, 53],
        [34, 20, 53],
        ...,
        [76, 76, 52],
        [76, 76, 52],
        [76, 76, 50]]], shape=(1080, 1616, 3), dtype=uint8)